# Generated by Django 5.0.6 on 2024-06-09 14:25
from decimal import Decimal
import django.db.models.deletion
import django_extensions.db.fields
import trading.constants
from django.conf import settings
from django.db import migrations, models


def create_stocks(apps, schema):
    Stock = apps.get_model("trading", "Stock")

    stocks = [
        Stock(name="Tesla Inc", symbol="TSLA", price=Decimal("177.48")),
        Stock(name="Apple Inc", symbol="AAPL", price=Decimal("196.89")),
        Stock(name="NVIDIA Corp", symbol="NVDA", price=Decimal("1208.88")),
        Stock(name="Advanced Micro Devices, Inc.", symbol="AMD", price=Decimal("167.87")),
        Stock(name="Meta Platforms Inc", symbol="META", price=Decimal("492.96")),
    ]
    Stock.objects.bulk_create(stocks)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('symbol', models.CharField(max_length=5, verbose_name='Symbol')),
                ('price', models.DecimalField(decimal_places=5, help_text='Price in USD', max_digits=32, verbose_name='Price')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quantity', models.BigIntegerField(verbose_name='Quantity')),
                ('order_type', models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell')], verbose_name='Order Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.stock', verbose_name='Stock')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(trading.constants.OrderTypes, models.Model),
        ),
        migrations.RunPython(create_stocks, migrations.RunPython.noop),

    ]
